routes/web.php
<?php

use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [PostController::class, 'index'])->name('posts.index');
Route::resource("posts", PostController::class)->except('index')->middleware('auth');
Route::get('/login', [PostController::class, 'login'])->name('login');
Route::get('/logout', [PostController::class, 'logout'])->name('logout');
Route::post('/login', [PostController::class, 'handleLogin']);

// Route::get('/', function () {
//     return view('welcome');
// });

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected $table = "category";

    public function posts(){
        return $this->hasMany(Post::class);
    }

}

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    use HasFactory;
    

    protected $guarded = [];

    public function user(){
        return $this->belongsTo(User::class);
    }
    public function category(){
        return $this->belongsTo(Category::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function posts(){
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use App\Models\Category;
use App\Http\Requests\StorePostRequest;
use App\Http\Requests\UpdatePostRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::with('category', 'user')->paginate(6);

        return view('posts.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $post = new Post();
        $categories = Category::all();

        return view('posts.create', compact('post', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StorePostRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePostRequest $request)
    {
        $user_id = Auth::user()->id;
        $data = $request->all();

        $online = array_key_exists('online', $data) ? $data['online'] : 0;

        Post::create([
            'title' => $data['title'],
            'content' => $data['content'],
            'category_id' => $data['category_id'],
            'user_id' => $user_id,
            'online' => ($online == 'on' ? 1 : 0),
        ])->saveOrFail();

        session()->flash("status", 'post creer avec success');
        return redirect()->route('posts.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        $categories = Category::all();
        return view('posts.update', compact('post', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdatePostRequest  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePostRequest $request, Post $post)
    {
        if (! Gate::allows('update-post', $post)) {
            session()->flash("error", 'vous n\'avez pas le droit de modifier le post');
            return back();
        }

        $user_id = Auth::user()->id;
        $data = $request->all();

        $online = array_key_exists('online', $data) ? $data['online'] : 0;

        $post->update([
            'title' => $data['title'],
            'content' => $data['content'],
            'category_id' => $data['category_id'],
            'user_id' => $user_id,
            'online' => ($online == 'on' ? 1:0)
        ]);

        session()->flash("status", 'post modifier avec success');
        return redirect()->route('posts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        $post->delete();
        session()->flash('status', 'post suprimer avec success');
        return redirect()->route('posts.index');
        //
    }


    public function login(){
        return view('login');
    }

    public function handleLogin(Request $request){
        $credentials = $request->validate([
            'email' => ['required', 'email'],
            'password' => ['required'],
        ]);

        if (Auth::attempt($credentials)) {
            $request->session()->regenerate();

            return redirect()->route('posts.index');
        }

        return back()->withErrors([
            'email' => 'The provided credentials do not match our records.',
        ])->onlyInput('email');
    }

    public function logout(Request $request){
        Auth::logout();

        $request->session()->invalidate();

        $request->session()->regenerateToken();

        return redirect()->route('login');
    }
}

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
    <title>post - @yield('title')</title>
    <style>
        @import url(https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;800;900&display=swap);

        *{
            margin: 0;
            padding: 0;
        }
        a:hover,
        a{
            text-decoration: none;
            color:white;
        }
        body {
          font-family: 'Poppins', sans-serif;
          font-size: 1rem;
          min-height: 100vh;
        }
        .logo{
            font-size: 2rem;
            font-weight: 800;
            text-transform: uppercase;
        }
        nav .logo span{
            color: rgb(1, 238, 206);
        }

    </style>
</head>
<body>
    <header class="bg-primary py-3">
        <nav class="d-flex container justify-content-between align-items-center">
            <a href="{{ route('posts.index') }}" class="logo">Post<span>APP</span> </a>
            <ul class="menu-list m-0">
                <li class="menu-item d-inline"><a href="{{ route('posts.index') }}">Accueil</a></li>
                @auth()
                <li class="menu-item d-inline ml-4"><a href="{{ route('posts.create') }}">creer</a></li>
                <li class="menu-item d-inline ml-4"><a href="{{ route('logout') }}">deconnexion</a></li>
                @else
                <li class="menu-item d-inline ml-4"><a href="{{ route('login') }}">Connexion</a></li>
                @endauth
            </ul>
        </nav>
    </header>

    @component('components.sesion') @endcomponent
    <div class="container mt-4">
        @yield('content')
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" ></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js"></script>
</body>
</html>

resources/views/login.blade.php
@extends('layout')

@section('title', 'login')

@section('content')
    <div class="form-container w-50 m-auto">
        <form action="" method="post">
            @csrf
            @component('components.input', [
                'title' => 'Email',
                'name' => 'email',
                'type' => 'email',
                'value' => 'admin@admin.com'
            ])
            @endcomponent
            @component('components.input', [
                'title' => 'Mot de passe',
                'name' => 'password',
                'type' => 'password',
                'value' => 'adminadmin'
            ])
            @endcomponent


            <button type="submit" class="btn btn-md btn-primary">login</button>
        </form>
    </div>
@endsection

resources/views/posts/create.blade.php
@extends('layout')

@section('title', 'home')

@section('content')
    <div class="form-container w-50 m-auto">
        <form action="{{ route('posts.store') }}" method="post">
            @csrf
            @component('components.input', [
                'title' => 'Title',
                'name' => 'title',
                'type' => 'text',
                'value' => 'un titre de test'
            ])
            @endcomponent
            @component('components.input', [
                'title' => 'Categories',
                'name' => 'category_id',
                'type' => 'select',
                'options' => $categories,
                'value' => $post->category_id
            ])
            @endcomponent


            @component('components.input', [
                'title' => 'Description',
                'name' => 'content',
                'type' => 'textarea',
                'value' => "une description de test"
            ])
            @endcomponent
            @component('components.input', [
                'title' => 'En ligne ?',
                'name' => 'online',
                'type' => 'checkbox',
                'value' => True
            ])
            @endcomponent


            <button type="submit" class="btn btn-md btn-primary">Enregistrer</button>
        </form>
    </div>
@endsection

resources/views/posts/index.blade.php
@extends('layout')

@section('title', 'home')

@section('content')

    <div class="d-flex flex-wrap">
        @foreach($posts as $post)
            <div class="col-md-4 py-3">
                <div class="card w-100">
                    <div class="card-body">
                        <h5 class="card-title">{{ Str::limit($post->title, 25) }}  </h5>
                        <span class="badge mb-1 badge-primary">{{ $post->category->name }}</span>
                        <p class="card-text">{{ Str::limit($post->content, 55) }}</p>
                        <div class="d-flex">
                            <a href="{{ route('posts.show', $post->id) }}" class="btn btn-primary">
                                <i class="fa-regular fa-pen-to-square"></i>
                            </a>
                            <form action="{{ route('posts.destroy', $post) }}" method="post">
                                @method('DELETE')
                                @csrf
                                <button type="submit" class="btn btn-danger ml-2">
                                    <i class="fas fa-trash"></i>
                                </button>
                            </form>
                        </div>
                    </div>
                    <div class="card-footer bg-transparent text-muted text-small border-0">
                        <small>Depuis le {{ $post->created_at->format('d M Y') }} par {{ $post->user->name }} </small>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
    {{ $posts->links() }}
@endsection

resources/views/posts/update.blade.php
@extends('layout')

@section('title', 'home')

@section('content')
    <div class="form-container w-50 m-auto">
        <form action="{{ route('posts.update', $post) }}" method="post">
            @method('PUT')
            @csrf
            @component('components.input', [
                'title' => 'Title',
                'name' => 'title',
                'type' => 'text',
                'value' => $post->title
            ])
            @endcomponent
            @component('components.input', [
                'title' => 'Categories',
                'name' => 'category_id',
                'type' => 'select',
                'options' => $categories,
                'value' => $post->category_id
            ])
            @endcomponent


            @component('components.input', [
                'title' => 'Description',
                'name' => 'content',
                'type' => 'textarea',
                'value' => $post->content
            ])
            @endcomponent
            @component('components.input', [
                'title' => 'En ligne ?',
                'name' => 'online',
                'type' => 'checkbox',
                'value' => $post->online
            ])
            @endcomponent


            <button type="submit" class="btn btn-md btn-primary">Modifier</button>
        </form>
    </div>
@endsection